name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2

jobs:
  windows_bundler:
    name: Bundler on Windows (${{ matrix.ruby.name }})

    runs-on: windows-2019

    env:
      RGV: ..

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: ruby-2.7, value: 2.7.2 }

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
        shell: bash
      - name: Run specs
        run: |
          bin/rspec spec/install/gemfile/force_spec.rb:7
        working-directory: ./bundler
        shell: bash
        if: "!startsWith(matrix.ruby.name, 'jruby')"
